docs: clarified the behavior when waited timeout.
openresty/lua-resty-shell pull request #6
Opened 2019-02-25 02:26 UTC by spacewander

2019-02-25 19:32 UTC, agentzh requested changes

2019-02-25 19:32 UTC, agentzh commented on README.md
> +expires, the sub-process will be killed by first a SIGTERM, and then a SIGKILL.
"the timeout expires" does not make sense. Should be "the timeout threshold is exceeded"?

Also, we need to make it clear about

1. the `SIGKILL` won't be issued when `SIGTERM` already makes the process quit.
1. the waiting time between `SIGTERM` and `SIGKILL`.
1 whether we always wait the full delay between `SIGTERM` and `SIGKILL` even if the process quits almost immediately upon receiving the `SIGTERM` signal.

2019-02-25 19:32 UTC, agentzh commented on README.md
> +Note that we do nothing with the child processes of the sub-process (if there are),
"do nothing" is ambiguous. We should say "do not automatically kill the sub-process".

2019-02-25 19:33 UTC, agentzh commented
"when waited timeout" is not proper English in the title, BTW. Maybe should be "when waiting is timed out"? Does it only applies to `:wait()` at all? It's not clear to me.

2019-02-26 02:33 UTC, spacewander commented
@agentzh 
Updated, and yes, the clean up only happens when waiting timed out.

2019-02-26 06:52 UTC, agentzh requested changes

2019-02-26 06:52 UTC, agentzh commented on README.md
> +threshold is exceeded, the sub-process will be killed by first a SIGTERM. Then we will
"by first a SIGTERM" is not proper English. I think you can write this:

> will be killed like this:
> 
> 1. first send a SIGTERM signal, and then
> 2. after 1 millisecond, sending a SIGKILL signal.

BTW, I do believe `1ms` is too soon. Many processes may take much longer than 1ms to clean up. How about 100ms instead?

2019-02-26 06:52 UTC, agentzh commented on README.md
> +Note that we do not automatically kill the child processes of the sub-process (if there are),
"if there are" => "if any".

2019-08-13 01:28 UTC, thibaultcha commented
Merged with the proper edits. Thanks!

2019-08-13 01:28 UTC, closed without merging